package service

const (
	ACTION_CHAT                              = 0
	//
	ACTION_GET_FRIEND_LIST                   = 10 // get friend list of userId
	ACTION_GET_FRIEND_INFO                   = 11 // userId requests targetId's info
	ACTION_UPDATE_INFO                       = 12 // update userId's info(risk -- not recommend)
	// Friend
	ACTION_FRIEND_ONLINE                     = 20 //
	ACTION_FRIEND_OFFLINE                    = 21 //
	//
	ACTION_FRIEND_APPLIED                    = 22
	ACTION_FRIEND_ACCEPTED                   = 23
	ACTION_FRIEND_REJECTED                   = 24
	ACTION_FRIEND_BROKEUP                    = 25
	ACTION_FRIEND_RECOMMENDED                = 26
	// Group
	ACTION_GET_GROUP_LIST                    = 30
	ACTION_GET_GROUP_INFO                    = 31
	ACTION_UPDATE_GROUP_INFO                 = 32
	ACTION_GET_GROUP_MEMBERS                 = 33
	//
	ACTION_GROUP_CREATED                     = 41
	ACTION_GROUP_DISMISSED                   = 42
	ACTION_GROUP_MASTER_CHANGED              = 43
	ACTION_GROUP_ADMIN_PROMOTED              = 44
	ACTION_GROUP_ADMIN_DEMOTED               = 45
	ACTION_GROUP_JOIN_APPLIED                = 47
	ACTION_GROUP_JOIN_ACCEPTED               = 48
	ACTION_GROUP_JOIN_REJECTED               = 49
	ACTION_GROUP_MEMBER_TOKEN                = 46
	ACTION_GROUP_MEMBER_LEFT                 = 50
	ACTION_GROUP_MEMBER_KICKED               = 51
	//
	//
	CODE_SUCCESS                             = 200
	CODE_FAILURE                             = 400
	//
	CODE_FRIEND_MAKING_ERROR                 = 10000
	CODE_FRIEND_NOTIFY_MAKING_APPLIED_ERROR  = 10001
	CODE_FRIEND_NOTIFY_MAKING_ACCEPTED_ERROR = 10002
	CODE_FRIEND_NOTIFY_MAKING_REJECTED_ERROR = 10003
	CODE_FRIEND_BREAKUP_ERROR                = 10004
	CODE_FRIEND_NOTIFY_BROKEUP_ERROR         = 10005
	CODE_FRIEND_RECOMMENDED_USER_ERROR       = 10006
	CODE_FRIEND_NOTIFY_RECOMMENDED_ERROR     = 10007
	//
	CODE_GROUP_CREATE_ERROR                  = 10101
	CODE_GROUP_DISMISS_ERROR                 = 10102
	CODE_GROUP_MASTER_CHANGE_ERROR           = 10103
	CODE_GROUP_ADMIN_PROMOTE_ERROR           = 10104
	CODE_GROUP_ADMIN_DEMOTE_ERROR            = 10105
	CODE_GROUP_JOIN_APPLY_ERROR              = 10106
	CODE_GROUP_JOIN_ACCEPT_ERROR             = 10107
	CODE_GROUP_JOIN_REJECT_ERROR             = 10108
	CODE_GROUP_MEMBER_TAKE_ERROR             = 10109
	CODE_GROUP_MEMBER_LEAVE_ERROR            = 10110
	CODE_GROUP_MEMBER_KICK_ERROR             = 10111

	CODE_GROUP_NOTIFY_CREATED_ERROR          = 10201
	CODE_GROUP_NOTIFY_DISMISSED_ERROR        = 10202
	CODE_GROUP_NOTIFY_MASTER_CHANGED_ERROR   = 10203
	CODE_GROUP_NOTIFY_ADMIN_PROMOTED_ERROR   = 10204
	CODE_GROUP_NOTIFY_ADMIN_DEMOTED_ERROR    = 10205
	CODE_GROUP_NOTIFY_JOIN_APPLIED_ERROR     = 10206
	CODE_GROUP_NOTIFY_JOIN_ACCEPTED_ERROR    = 10207
	CODE_GROUP_NOTIFY_JOIN_REJECTED_ERROR    = 10208
	CODE_GROUP_NOTIFY_MEMBER_TOKEN_ERROR     = 10209
	CODE_GROUP_NOTIFY_MEMBER_LEFT_ERROR      = 10210
	CODE_GROUP_NOTIFY_MEMBER_KICKED_ERROR    = 10211
)